repos:
- repo: https://github.com/google/yapf
  rev: 'v0.32.0'
  hooks:
  - id: yapf
- repo: https://github.com/PyCQA/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    additional_dependencies:
    - pep8-naming==0.12.1
    - pydocstyle==6.1.1
    - flake8-docstrings==1.6.0
    - flake8-rst-docstrings==0.2.3
