[package]
name = "schmeud"
version = "0.9.0"
edition = "2018"

[lib]
name = "schmeud"
crate-type = ["cdylib"]

[dependencies]
num = "0.4"
ndarray = {version = "0.15", features = ["approx"]}
ndarray-linalg = { version = "0.14" }
ndarray-rand = "0.14"
numpy = "0.16"
petgraph = "0.6"
itertools-num = "0.1.3"

[features]
# Enables parallel processing support by enabling the "rayon" feature of jpeg-decoder.
default = ["openblas-static"]
openblas-static = ["ndarray-linalg/openblas-static"]
openblas-system = ["ndarray-linalg/openblas-system"]
rayon = ["ndarray/rayon"]


[dependencies.pyo3]
version = "0.16"
features = ["extension-module"]

[package.metadata.maturin]
name = "schmeud._schmeud"