[package]
name = "schmeud"
version = "0.9.0"
edition = "2018"

[lib]
name = "schmeud"
crate-type = ["cdylib"]

[dependencies]
num = "0.4"
ndarray = {version = "0.15", features = ["rayon", "approx"]}
ndarray-linalg = { version = "0.14", features = ["openblas-static"] }
ndarray-rand = "0.14"
numpy = "0.16"
petgraph = "0.6"
itertools-num = "0.1.3"

[dependencies.pyo3]
version = "0.16"
features = ["extension-module"]

[package.metadata.maturin]
python-source = "python_src"