[package]
name = "schmeud"
version = "0.0.1"
edition = "2021"

[lib]
name = "schmeud"
crate-type = ["cdylib"]

[dependencies]
num = "0.4"
ndarray = {version = "0.15", features = ["approx"]}
ndarray-linalg = { version = "0.15" }
ndarray-rand = "0.14"
numpy = "0.17"
petgraph = "0.6"
itertools-num = "0.1.3"

[dependencies.pyo3]
version = "0.17"
features = ["extension-module"]

[features]
default = ["openblas-static"]
openblas-static = ["ndarray-linalg/openblas-static"]
openblas-system = ["ndarray-linalg/openblas-system"]
rayon = ["ndarray/rayon"]

[package.metadata.maturin]
name = "schmeud._schmeud"