[package]
name = "schmeud"
version = "0.1.0"
edition = "2018"

[lib]
name = "schmeud"
crate-type = ["cdylib", "lib"]

[dependencies]
num = "0.4"
ndarray = {version = "0.15", features = ["rayon", "approx"]}
ndarray-linalg = { version = "0.14", features = ["openblas-system"] }
ndarray-rand = "0.14"
numpy = "0.14.1"

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]

[package.metadata.maturin]
python-source = "python_src"