[project]
name = "schmeud"
version = "0.8.1"
dependencies = [
    "freud-analysis>=2.7.0",
    "gsd>=2.5.1",
    "pandas>=1.3.4",
    "numpy<1.21",
    "scikit-learn>=1.0",
    "numba>=0.54"
]

[virtualenvs]
create = true
in-project = true

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"