[project]
name = "schmeud"
version = "0.2.0"
dependencies = [
    "freud-analysis>=2.7.0",
    "gsd>=2.5.1",
    "pandas",
    "scikit-learn"
]

[virtualenvs]
create = true
in-project = true

[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"