name: test-schmeud

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'pyproject.toml'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Rust tests
        run: cargo test
        
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python tests
        run: |
          python3 -m venv venv3
          source venv3/bin/activate
          python3 -m pip install maturin>=1.0 pytest==7.1.2
          maturin develop
          pytest