name: test-wheels

on: push

jobs:

  linux-wheels:
    if: contains(github.event.head_commit.message, 'test-wheels')
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build wheels
        run: |
          yum install -y openssl-devel
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          bash .github/workflows/build-wheels.sh